stages:
  - check_vars
  - pull
  - build
  - migration
  - run

check_vars:
  stage: check_vars
  script:
    - |
      if [ -z "$DOMAIN" ] || \
      [ -z "$IDF_TOKEN" ] || \
      [ -z "$POSTGRES_USER" ] || \
      [ -z "$POSTGRES_PASS" ] || \
      [ -z "$SECRET" ] || \
      [ -z "$EMAIL" ] || \
      [ -z "$IS_TESTING" ] || \
      [ -z "$DOTENV_FILE" ] || \
      [ -z "$HASHPASS_ADMIN" ] || \
      [ -z "$GOOGLE_CLIENT_ID" ] || \
      [ -z "$GOOGLE_CLIENT_SECRET" ] || \
      [ -z "$INFLUXDB_PASSWORD" ] || \
      [ -z "$INFLUXDB_USERNAME" ]; then
        echo "Error: Missing one or more required environment variables."
        exit 1
      fi

pull:
  stage: pull
  when: on_success
  needs:
    - check_vars
  script:
    - git config --global --add safe.directory /usr/homeserver
    - cd /usr/homeserver
    - git pull
    - cp $DOTENV_FILE /usr/homeserver/react-app/.env

build:
  stage: build
  when: on_success
  needs:
    - pull
  script:
    - cd /usr/homeserver
    - docker compose build

migration_auto:
  stage: migration
  script:
    - cd /usr/homeserver
    - docker compose run homescreen alembic upgrade head
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /[(?i)migration]/
      when: on_success
      needs:
        - build

migration_manual:
  stage: migration
  when: manual
  script:
    - cd /usr/homeserver
    - docker compose run homescreen alembic upgrade head

run:
  stage: run
  when: on_success
  needs:
      - build
  script:
    - cd /usr/homeserver
    - docker compose up -d
