"""refresh_tokens table added, deleted incr from users

Revision ID: 9e3c2bfa608c
Revises: 8109c1af4139
Create Date: 2024-07-14 19:30:45.488662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e3c2bfa608c'
down_revision = '8109c1af4139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name='fk_refresh_tokens_users_uuid_user_id'),
    sa.PrimaryKeyConstraint('token')
    )
    op.drop_column('users', 'refresh_token_incr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_incr', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
