"""scopes in User

Revision ID: c7c3cfec8447
Revises: be31ac52fae3
Create Date: 2024-06-09 23:52:18.421601

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c7c3cfec8447'
down_revision = 'be31ac52fae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scopes', sa.String(length=256), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'scopes')
    # ### end Alembic commands ###