global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: node-nl
    static_configs:
      - targets: [ 'node-exporter.local:9100' ]

  - job_name: node-ru
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: traefik
    static_configs:
      - targets: [ 'traefik-nl.local:8899' ]

  - job_name: postgres
    static_configs:
      - targets: [ 'postgres-exporter.local:9187' ]

  - job_name: mongo
    static_configs:
      - targets: [ 'mongo-exporter.local:9216' ]