global:
  scrape_interval: 15s


scrape_configs:
#  - job_name: prometheus
#    static_configs:
#      - targets: [ 'prometheus:9090' ]

  - job_name: node
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: traefik
    static_configs:
      - targets: [ 'traefik:8899' ]